name: Weekly Netlify Rebuild

on:
  schedule:
    - cron: "0 5 * * 0" # Sunday at 5:00 UTC

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: curl --fail --request POST --data '{}' https://api.netlify.com/build_hooks/69f2695bdbd177122d411c3e
